export type ArticleCategory =
  | "family-protection"
  | "mortgage-protection"
  | "final-expense"
  | "retirement"
  | "parents"
  | "seniors"
  | "estate-planning"
  | "veterans";

export interface Article {
  slug: string;
  title: string;
  excerpt: string;
  category: ArticleCategory;
  readTime: number; // minutes
  publishDate: string;
  featured?: boolean;
  tags?: string[];
}

export const CATEGORY_META: Record<
  ArticleCategory,
  { label: string; description: string; color: string; icon: string }
> = {
  "family-protection": {
    label: "Family Protection",
    description: "Guides to protecting your family's financial future with the right life insurance coverage.",
    color: "from-blue-50 to-indigo-50",
    icon: "Users",
  },
  "mortgage-protection": {
    label: "Mortgage Protection",
    description: "Everything you need to know about keeping your family in their home.",
    color: "from-emerald-50 to-teal-50",
    icon: "Home",
  },
  "final-expense": {
    label: "Final Expense",
    description: "Learn how to plan ahead so your loved ones aren't burdened by end-of-life costs.",
    color: "from-rose-50 to-pink-50",
    icon: "Heart",
  },
  retirement: {
    label: "Retirement",
    description: "Using life insurance as part of a smart retirement income strategy.",
    color: "from-amber-50 to-yellow-50",
    icon: "TrendingUp",
  },
  parents: {
    label: "Parents",
    description: "Insurance strategies designed specifically for parents of young children.",
    color: "from-purple-50 to-violet-50",
    icon: "Baby",
  },
  seniors: {
    label: "Seniors",
    description: "Tailored coverage options for adults 50, 60, 70, and beyond.",
    color: "from-sky-50 to-cyan-50",
    icon: "Star",
  },
  "estate-planning": {
    label: "Estate Planning",
    description: "Using life insurance to preserve your legacy and protect your estate.",
    color: "from-stone-50 to-gray-50",
    icon: "FileText",
  },
  veterans: {
    label: "Veterans",
    description: "Special coverage options and benefits available for veterans and military families.",
    color: "from-green-50 to-lime-50",
    icon: "Shield",
  },
};

export const ALL_ARTICLES: Article[] = [
  // ── FAMILY PROTECTION (25) ──────────────────────────────────────────
  {
    slug: "how-much-life-insurance-do-i-need",
    title: "How Much Life Insurance Do I Really Need?",
    excerpt: "Use our simple framework to calculate exactly how much coverage will protect your family — without overpaying.",
    category: "family-protection",
    readTime: 7,
    publishDate: "2024-10-15",
    featured: true,
    tags: ["coverage", "calculator", "planning"],
  },
  {
    slug: "term-vs-whole-life-which-is-right",
    title: "Term vs. Whole Life Insurance: Which Is Right for Your Family?",
    excerpt: "A side-by-side breakdown of the two most popular policy types so you can choose with confidence.",
    category: "family-protection",
    readTime: 9,
    publishDate: "2024-10-20",
    featured: true,
    tags: ["term life", "whole life", "comparison"],
  },
  {
    slug: "life-insurance-for-stay-at-home-parents",
    title: "Why Stay-at-Home Parents Need Life Insurance Too",
    excerpt: "The economic value of a stay-at-home parent is often underestimated. Here's how to protect it.",
    category: "family-protection",
    readTime: 6,
    publishDate: "2024-11-01",
    tags: ["parents", "stay at home"],
  },
  {
    slug: "what-happens-if-i-die-without-life-insurance",
    title: "What Happens to Your Family If You Die Without Life Insurance?",
    excerpt: "A candid look at the financial impact of being uninsured — and why a policy is one of the greatest gifts you can give.",
    category: "family-protection",
    readTime: 8,
    publishDate: "2024-11-05",
    tags: ["uninsured", "planning"],
  },
  {
    slug: "beneficiary-mistakes-to-avoid",
    title: "5 Beneficiary Mistakes That Could Cost Your Family Everything",
    excerpt: "Naming the wrong beneficiary — or forgetting to update it — can derail even the best-laid plans.",
    category: "family-protection",
    readTime: 5,
    publishDate: "2024-11-10",
    tags: ["beneficiary", "mistakes"],
  },
  {
    slug: "life-insurance-riders-explained",
    title: "Life Insurance Riders Explained: Customize Your Coverage",
    excerpt: "Accelerated death benefits, waiver of premium, child riders — here's what they mean and whether you need them.",
    category: "family-protection",
    readTime: 10,
    publishDate: "2024-11-15",
    tags: ["riders", "customization"],
  },
  {
    slug: "independent-broker-vs-captive-agent",
    title: "Independent Broker vs. Captive Agent: Why It Matters",
    excerpt: "Working with an independent broker means you get options from multiple carriers — not just one company's products.",
    category: "family-protection",
    readTime: 5,
    publishDate: "2024-11-20",
    tags: ["broker", "agent"],
  },
  {
    slug: "life-insurance-myths-debunked",
    title: "7 Life Insurance Myths That Are Costing Families Their Protection",
    excerpt: "\"It's too expensive\" and \"I'm too young\" are just two of the myths keeping families unprotected.",
    category: "family-protection",
    readTime: 7,
    publishDate: "2024-12-01",
    tags: ["myths", "education"],
  },
  {
    slug: "how-life-insurance-premiums-are-calculated",
    title: "How Life Insurance Premiums Are Calculated",
    excerpt: "Age, health, lifestyle, and coverage amount all factor in. Learn what carriers look at — and how to get the best rate.",
    category: "family-protection",
    readTime: 8,
    publishDate: "2024-12-05",
    tags: ["premiums", "underwriting"],
  },
  {
    slug: "best-age-to-buy-life-insurance",
    title: "The Best Age to Buy Life Insurance (Hint: It's Sooner Than You Think)",
    excerpt: "Every year you wait, premiums go up. Here's why locking in coverage early is one of the smartest financial moves.",
    category: "family-protection",
    readTime: 6,
    publishDate: "2024-12-10",
    tags: ["age", "timing"],
  },
  {
    slug: "life-insurance-for-young-adults",
    title: "Life Insurance for Young Adults in Their 20s and 30s",
    excerpt: "You're healthy, you're young — and that's exactly why now is the perfect time to lock in low rates.",
    category: "family-protection",
    readTime: 6,
    publishDate: "2024-12-15",
    tags: ["young adults", "millennials"],
  },
  {
    slug: "life-insurance-medical-exam-what-to-expect",
    title: "The Life Insurance Medical Exam: What to Expect",
    excerpt: "No-exam policies exist, but a medical exam often gets you better rates. Here's how to prepare.",
    category: "family-protection",
    readTime: 7,
    publishDate: "2024-12-20",
    tags: ["medical exam", "underwriting"],
  },
  {
    slug: "no-exam-life-insurance-pros-cons",
    title: "No-Exam Life Insurance: Pros, Cons, and Who It's Best For",
    excerpt: "Instant approval sounds great — but simplified issue policies come with trade-offs worth understanding.",
    category: "family-protection",
    readTime: 7,
    publishDate: "2025-01-05",
    tags: ["no exam", "simplified issue"],
  },
  {
    slug: "life-insurance-for-smokers",
    title: "Life Insurance for Smokers: What You Need to Know",
    excerpt: "Smokers pay more for coverage — but by how much, and what can you do about it?",
    category: "family-protection",
    readTime: 6,
    publishDate: "2025-01-10",
    tags: ["smokers", "health"],
  },
  {
    slug: "life-insurance-with-pre-existing-conditions",
    title: "Can I Get Life Insurance with Pre-Existing Conditions?",
    excerpt: "Diabetes, heart disease, cancer history — many conditions are still insurable. Here's what to know.",
    category: "family-protection",
    readTime: 9,
    publishDate: "2025-01-15",
    tags: ["health conditions", "underwriting"],
  },
  {
    slug: "how-to-compare-life-insurance-quotes",
    title: "How to Compare Life Insurance Quotes the Right Way",
    excerpt: "Price matters, but it's only one factor. Learn what else to look for when evaluating policies.",
    category: "family-protection",
    readTime: 7,
    publishDate: "2025-01-20",
    tags: ["quotes", "comparison"],
  },
  {
    slug: "laddering-life-insurance-policies",
    title: "Laddering Life Insurance Policies: A Smart Strategy for Families",
    excerpt: "Stacking multiple term policies can maximize coverage during your highest-need years while minimizing cost.",
    category: "family-protection",
    readTime: 8,
    publishDate: "2025-01-25",
    tags: ["strategy", "laddering"],
  },
  {
    slug: "dual-income-household-insurance-needs",
    title: "Life Insurance for Dual-Income Households",
    excerpt: "When both spouses earn income, the coverage math changes. Here's how to protect both earners.",
    category: "family-protection",
    readTime: 6,
    publishDate: "2025-02-01",
    tags: ["dual income", "couples"],
  },
  {
    slug: "life-insurance-policy-review-checklist",
    title: "Life Insurance Policy Review: A Checklist for Every Major Life Event",
    excerpt: "Marriage, new baby, new home — these milestones should trigger a policy review. Here's your checklist.",
    category: "family-protection",
    readTime: 5,
    publishDate: "2025-02-05",
    tags: ["review", "life events"],
  },
  {
    slug: "replacing-employer-life-insurance",
    title: "Why Employer-Provided Life Insurance Is Never Enough",
    excerpt: "Group coverage is a great perk, but relying on it alone leaves your family exposed. Here's why.",
    category: "family-protection",
    readTime: 6,
    publishDate: "2025-02-10",
    tags: ["employer", "group coverage"],
  },
  {
    slug: "life-insurance-for-business-owners",
    title: "Life Insurance for Business Owners: Key Man & Buy-Sell Agreements",
    excerpt: "If your business depends on you, your family — and your partners — need protection.",
    category: "family-protection",
    readTime: 9,
    publishDate: "2025-02-15",
    tags: ["business owners", "key man"],
  },
  {
    slug: "how-death-benefit-is-paid",
    title: "How a Life Insurance Death Benefit Is Paid Out",
    excerpt: "Lump sum, installments, or annuity — understanding your options helps your family plan ahead.",
    category: "family-protection",
    readTime: 5,
    publishDate: "2025-02-20",
    tags: ["death benefit", "payout"],
  },
  {
    slug: "life-insurance-taxes",
    title: "Is Life Insurance Tax-Free? What Your Family Needs to Know",
    excerpt: "Death benefits are generally income-tax-free — but there are exceptions and estate tax nuances.",
    category: "family-protection",
    readTime: 7,
    publishDate: "2025-03-01",
    tags: ["taxes", "estate"],
  },
  {
    slug: "what-to-do-after-spouse-dies",
    title: "What to Do with Life Insurance Money After a Spouse Dies",
    excerpt: "Receiving a death benefit can be overwhelming. Here's a practical, compassionate guide for surviving spouses.",
    category: "family-protection",
    readTime: 8,
    publishDate: "2025-03-05",
    tags: ["spouse", "death benefit", "grief"],
  },
  {
    slug: "life-insurance-cash-value-explained",
    title: "Cash Value Life Insurance: How It Works and When It Makes Sense",
    excerpt: "Whole and universal life policies build cash value over time. Is that a feature worth paying for?",
    category: "family-protection",
    readTime: 9,
    publishDate: "2025-03-10",
    tags: ["cash value", "whole life", "universal life"],
  },

  // ── MORTGAGE PROTECTION (25) ─────────────────────────────────────────
  {
    slug: "what-is-mortgage-protection-insurance",
    title: "What Is Mortgage Protection Insurance and Do You Need It?",
    excerpt: "Mortgage protection insurance pays off your home loan if you die — keeping your family housed when they need it most.",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2024-10-18",
    featured: true,
    tags: ["basics", "overview"],
  },
  {
    slug: "mortgage-protection-vs-pmi",
    title: "Mortgage Protection Insurance vs. PMI: What's the Difference?",
    excerpt: "These two products sound similar but serve very different purposes. Don't confuse them.",
    category: "mortgage-protection",
    readTime: 5,
    publishDate: "2024-10-25",
    tags: ["PMI", "comparison"],
  },
  {
    slug: "mortgage-protection-vs-term-life",
    title: "Mortgage Protection vs. Term Life Insurance: Which Should You Buy?",
    excerpt: "Both can cover your mortgage — but one gives your family far more flexibility. Here's the breakdown.",
    category: "mortgage-protection",
    readTime: 8,
    publishDate: "2024-11-02",
    tags: ["term life", "comparison"],
  },
  {
    slug: "how-much-mortgage-protection-coverage",
    title: "How Much Mortgage Protection Coverage Do You Actually Need?",
    excerpt: "Should you insure the full balance, or just a portion? We break down the calculation.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2024-11-08",
    tags: ["coverage amount", "calculator"],
  },
  {
    slug: "mortgage-protection-for-new-homeowners",
    title: "Mortgage Protection Insurance for First-Time Homeowners",
    excerpt: "Just bought your first home? Here's why mortgage protection should be your next conversation.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2024-11-12",
    tags: ["first home", "new homeowner"],
  },
  {
    slug: "mortgage-protection-denied-what-to-do",
    title: "Denied for Mortgage Protection Insurance? Here Are Your Options",
    excerpt: "Health issues can make approval harder — but options still exist, including guaranteed issue policies.",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2024-11-18",
    tags: ["denial", "alternatives"],
  },
  {
    slug: "mortgage-protection-with-disability-rider",
    title: "Adding a Disability Rider to Your Mortgage Protection Policy",
    excerpt: "Death isn't the only risk to your mortgage. A disability rider pays if you can't work.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2024-12-03",
    tags: ["disability", "riders"],
  },
  {
    slug: "mortgage-protection-after-refinancing",
    title: "Do I Need to Update My Mortgage Protection Policy After Refinancing?",
    excerpt: "When you refi, your loan balance and terms change. Your insurance should too.",
    category: "mortgage-protection",
    readTime: 5,
    publishDate: "2024-12-08",
    tags: ["refinancing", "review"],
  },
  {
    slug: "decreasing-term-mortgage-protection",
    title: "Decreasing Term Policies: Are They Good for Mortgage Protection?",
    excerpt: "Some policies shrink alongside your mortgage balance. Here's whether that's a smart trade-off.",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2024-12-12",
    tags: ["decreasing term", "policy type"],
  },
  {
    slug: "mortgage-protection-for-self-employed",
    title: "Mortgage Protection for Self-Employed Homeowners",
    excerpt: "Variable income complicates coverage decisions. Here's how to protect your home when you work for yourself.",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2024-12-18",
    tags: ["self-employed", "freelance"],
  },
  {
    slug: "joint-mortgage-protection-policy",
    title: "Joint Mortgage Protection: Insuring Both Spouses on One Policy",
    excerpt: "A joint policy can be simpler and sometimes cheaper — but it's not right for everyone.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2025-01-03",
    tags: ["joint policy", "couples"],
  },
  {
    slug: "mortgage-protection-return-of-premium",
    title: "Return of Premium Mortgage Protection: Is It Worth It?",
    excerpt: "Get your premiums back if you outlive the policy — but the higher cost might not pencil out.",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2025-01-08",
    tags: ["return of premium", "ROP"],
  },
  {
    slug: "what-happens-to-mortgage-when-spouse-dies",
    title: "What Happens to Your Mortgage When a Spouse Dies?",
    excerpt: "The mortgage doesn't disappear. Here's what surviving spouses need to know — and how protection helps.",
    category: "mortgage-protection",
    readTime: 8,
    publishDate: "2025-01-12",
    tags: ["spouse", "death"],
  },
  {
    slug: "mortgage-protection-older-homeowners",
    title: "Mortgage Protection Insurance for Homeowners Over 50",
    excerpt: "Later in life, mortgage protection still makes sense — especially when you're carrying a large balance.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2025-01-18",
    tags: ["over 50", "seniors"],
  },
  {
    slug: "critical-illness-mortgage-rider",
    title: "Critical Illness Riders on Mortgage Protection Policies",
    excerpt: "A serious diagnosis could stop your income before it ends your life. Here's how to protect against that.",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2025-01-22",
    tags: ["critical illness", "riders"],
  },
  {
    slug: "mortgage-protection-for-rental-properties",
    title: "Can You Get Mortgage Protection Insurance on a Rental Property?",
    excerpt: "Investment properties carry different risks. Here's how landlords can protect rental income.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2025-01-28",
    tags: ["rental", "investment property"],
  },
  {
    slug: "bank-mortgage-insurance-vs-private",
    title: "Bank-Offered Mortgage Insurance vs. Private Coverage: A Comparison",
    excerpt: "Your lender may offer mortgage insurance at closing — but is it the best deal? Almost never.",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2025-02-03",
    tags: ["bank", "lender"],
  },
  {
    slug: "mortgage-protection-quotes-how-to-shop",
    title: "How to Shop for Mortgage Protection Insurance",
    excerpt: "The best policy isn't always the cheapest one. Here's how to compare coverage the smart way.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2025-02-08",
    tags: ["quotes", "shopping"],
  },
  {
    slug: "mortgage-protection-tax-deductible",
    title: "Is Mortgage Protection Insurance Tax Deductible?",
    excerpt: "In most cases, no — but there are nuances, especially for business owners and landlords.",
    category: "mortgage-protection",
    readTime: 5,
    publishDate: "2025-02-12",
    tags: ["taxes"],
  },
  {
    slug: "mortgage-protection-for-va-loans",
    title: "Mortgage Protection Insurance for VA Loan Holders",
    excerpt: "VA loans already offer some protections — but a dedicated policy adds a critical extra layer.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2025-02-18",
    tags: ["VA loan", "veterans"],
  },
  {
    slug: "how-long-does-mortgage-protection-last",
    title: "How Long Should Your Mortgage Protection Policy Last?",
    excerpt: "Your term should align with your loan payoff date — but life events can change the math.",
    category: "mortgage-protection",
    readTime: 5,
    publishDate: "2025-02-22",
    tags: ["term length", "planning"],
  },
  {
    slug: "mortgage-protection-single-parent",
    title: "Mortgage Protection for Single Parents: Why It's Non-Negotiable",
    excerpt: "When you're the only breadwinner and the only caregiver, protecting your home is protecting everything.",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2025-03-01",
    tags: ["single parent"],
  },
  {
    slug: "buying-home-without-mortgage-protection",
    title: "The Risks of Buying a Home Without Mortgage Protection",
    excerpt: "Most people insure the house itself — but forget to insure their ability to pay for it.",
    category: "mortgage-protection",
    readTime: 6,
    publishDate: "2025-03-06",
    tags: ["risk", "uninsured"],
  },
  {
    slug: "mortgage-protection-level-vs-decreasing",
    title: "Level vs. Decreasing Mortgage Protection: Which Is Better?",
    excerpt: "Level policies keep your benefit constant. Decreasing policies shrink as your balance does. Which wins?",
    category: "mortgage-protection",
    readTime: 7,
    publishDate: "2025-03-10",
    tags: ["level", "decreasing", "comparison"],
  },
  {
    slug: "mortgage-protection-checklist",
    title: "Mortgage Protection Insurance Checklist: Everything to Review Before Buying",
    excerpt: "Before you sign anything, run through this 10-point checklist to make sure you're getting real protection.",
    category: "mortgage-protection",
    readTime: 5,
    publishDate: "2025-03-14",
    tags: ["checklist", "buying guide"],
  },

  // ── FINAL EXPENSE (25) ──────────────────────────────────────────────
  {
    slug: "what-is-final-expense-insurance",
    title: "What Is Final Expense Insurance? A Complete Guide",
    excerpt: "Final expense insurance is designed to cover funeral costs and end-of-life bills. Here's everything you need to know.",
    category: "final-expense",
    readTime: 8,
    publishDate: "2024-10-22",
    featured: true,
    tags: ["basics", "overview"],
  },
  {
    slug: "average-funeral-cost-2024",
    title: "How Much Does a Funeral Cost in 2024?",
    excerpt: "The average funeral now costs between $8,000 and $12,000. Final expense insurance ensures your family isn't blindsided.",
    category: "final-expense",
    readTime: 6,
    publishDate: "2024-10-28",
    tags: ["costs", "planning"],
  },
  {
    slug: "burial-insurance-vs-final-expense",
    title: "Burial Insurance vs. Final Expense Insurance: Is There a Difference?",
    excerpt: "These terms are often used interchangeably — but there are subtle distinctions worth understanding.",
    category: "final-expense",
    readTime: 5,
    publishDate: "2024-11-04",
    tags: ["burial", "terminology"],
  },
  {
    slug: "final-expense-for-seniors-over-70",
    title: "Final Expense Insurance for Seniors Over 70: What You Need to Know",
    excerpt: "Coverage is still available in your 70s and 80s — often with no medical exam required.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2024-11-09",
    tags: ["seniors", "over 70"],
  },
  {
    slug: "guaranteed-issue-final-expense",
    title: "Guaranteed Issue Life Insurance: Who It's For and What to Expect",
    excerpt: "No health questions, no medical exam — but graded benefits and higher premiums are part of the deal.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2024-11-14",
    tags: ["guaranteed issue", "no exam"],
  },
  {
    slug: "simplified-issue-final-expense",
    title: "Simplified Issue Final Expense Insurance: Fast Approval, Better Rates",
    excerpt: "A few health questions, no medical exam, and coverage in as little as 24 hours.",
    category: "final-expense",
    readTime: 6,
    publishDate: "2024-11-19",
    tags: ["simplified issue"],
  },
  {
    slug: "how-much-final-expense-coverage-to-buy",
    title: "How Much Final Expense Coverage Do You Need?",
    excerpt: "We help you add up funeral costs, medical bills, and outstanding debts to land on the right number.",
    category: "final-expense",
    readTime: 6,
    publishDate: "2024-12-02",
    tags: ["coverage amount", "calculator"],
  },
  {
    slug: "final-expense-with-health-issues",
    title: "Can I Get Final Expense Insurance with Health Problems?",
    excerpt: "COPD, diabetes, heart disease — many conditions are still insurable. Here's how to find coverage.",
    category: "final-expense",
    readTime: 8,
    publishDate: "2024-12-07",
    tags: ["health conditions", "underwriting"],
  },
  {
    slug: "prepaid-funeral-vs-insurance",
    title: "Prepaid Funeral Plan vs. Final Expense Insurance: Which Is Better?",
    excerpt: "Both help cover funeral costs — but one is far more flexible when plans change.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2024-12-14",
    tags: ["prepaid funeral", "comparison"],
  },
  {
    slug: "final-expense-for-parents",
    title: "Buying Final Expense Insurance for Your Aging Parents",
    excerpt: "You can take out a policy on a parent — here's how the process works and what to discuss.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2024-12-19",
    tags: ["parents", "aging"],
  },
  {
    slug: "graded-death-benefit-explained",
    title: "Graded Death Benefit: What It Is and When It Applies",
    excerpt: "Some policies won't pay the full benefit if you die in the first two years. Here's what to know.",
    category: "final-expense",
    readTime: 6,
    publishDate: "2025-01-04",
    tags: ["graded benefit", "waiting period"],
  },
  {
    slug: "final-expense-carriers-compared",
    title: "Top Final Expense Insurance Carriers Compared",
    excerpt: "Americo, Mutual of Omaha, TransAmerica — how do the top carriers stack up on price and flexibility?",
    category: "final-expense",
    readTime: 9,
    publishDate: "2025-01-09",
    tags: ["carriers", "comparison"],
  },
  {
    slug: "how-to-plan-a-funeral-in-advance",
    title: "How to Plan Your Funeral in Advance (and Spare Your Family the Burden)",
    excerpt: "Pre-planning a funeral is one of the most loving things you can do. Here's a step-by-step guide.",
    category: "final-expense",
    readTime: 8,
    publishDate: "2025-01-14",
    tags: ["planning", "funeral"],
  },
  {
    slug: "cremation-vs-burial-cost",
    title: "Cremation vs. Burial: A Complete Cost Comparison",
    excerpt: "Cremation is generally less expensive — but costs vary widely. Here's what to budget for either choice.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2025-01-19",
    tags: ["cremation", "burial", "costs"],
  },
  {
    slug: "final-expense-for-low-income-seniors",
    title: "Affordable Final Expense Insurance for Seniors on a Fixed Income",
    excerpt: "Coverage starting at $20–$50/month is available. Here's how to find a policy that fits your budget.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2025-01-24",
    tags: ["affordable", "fixed income"],
  },
  {
    slug: "final-expense-for-diabetics",
    title: "Final Expense Insurance for Diabetics: Best Options in 2024",
    excerpt: "Diabetes doesn't mean uninsurable. Many carriers offer competitive rates for well-managed Type 1 and Type 2.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2025-01-29",
    tags: ["diabetes", "health conditions"],
  },
  {
    slug: "final-expense-policy-lapse-what-happens",
    title: "What Happens If Your Final Expense Policy Lapses?",
    excerpt: "Missed payments can cancel your coverage. Here's how to prevent lapses — and what to do if one happens.",
    category: "final-expense",
    readTime: 5,
    publishDate: "2025-02-04",
    tags: ["lapse", "payment"],
  },
  {
    slug: "final-expense-beneficiary-guide",
    title: "How to Choose and Update a Beneficiary for Your Final Expense Policy",
    excerpt: "The wrong beneficiary designation can send your death benefit to the wrong place. Here's how to get it right.",
    category: "final-expense",
    readTime: 5,
    publishDate: "2025-02-09",
    tags: ["beneficiary"],
  },
  {
    slug: "final-expense-for-obese-applicants",
    title: "Final Expense Insurance with High BMI: What Carriers Look For",
    excerpt: "Weight affects rates and approval — but many carriers still offer coverage at reasonable premiums.",
    category: "final-expense",
    readTime: 6,
    publishDate: "2025-02-14",
    tags: ["BMI", "weight", "health"],
  },
  {
    slug: "final-expense-vs-term-life",
    title: "Final Expense vs. Term Life Insurance: Which Is Right for You?",
    excerpt: "Term life offers larger coverage at lower cost — but final expense wins when you can't qualify for term.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2025-02-19",
    tags: ["term life", "comparison"],
  },
  {
    slug: "final-expense-face-amount-guide",
    title: "Choosing the Right Face Amount for Your Final Expense Policy",
    excerpt: "Too little leaves your family short. Too much wastes money. Here's how to land on the right number.",
    category: "final-expense",
    readTime: 5,
    publishDate: "2025-02-24",
    tags: ["face amount", "coverage"],
  },
  {
    slug: "final-expense-for-cancer-survivors",
    title: "Final Expense Insurance for Cancer Survivors",
    excerpt: "Your options depend on how long you've been in remission. Here's what to expect from underwriters.",
    category: "final-expense",
    readTime: 7,
    publishDate: "2025-03-02",
    tags: ["cancer", "health conditions"],
  },
  {
    slug: "what-is-a-good-final-expense-rate",
    title: "What Is a Good Monthly Rate for Final Expense Insurance?",
    excerpt: "Rates depend on age, health, and coverage amount. Here are realistic benchmarks for every profile.",
    category: "final-expense",
    readTime: 6,
    publishDate: "2025-03-07",
    tags: ["rates", "pricing"],
  },
  {
    slug: "final-expense-claim-process",
    title: "How to File a Final Expense Insurance Claim",
    excerpt: "When the time comes, your family needs simplicity. Here's what the claim process looks like.",
    category: "final-expense",
    readTime: 5,
    publishDate: "2025-03-12",
    tags: ["claims", "process"],
  },
  {
    slug: "final-expense-policy-for-spouse",
    title: "Should You Buy Final Expense Coverage for Your Spouse?",
    excerpt: "Both partners should have coverage — especially if one handles most of the household finances.",
    category: "final-expense",
    readTime: 5,
    publishDate: "2025-03-16",
    tags: ["spouse", "couples"],
  },

  // ── RETIREMENT (25) ─────────────────────────────────────────────────
  {
    slug: "life-insurance-in-retirement-planning",
    title: "How Life Insurance Fits Into Your Retirement Plan",
    excerpt: "Life insurance isn't just for young families — it can play a powerful role in retirement income strategy.",
    category: "retirement",
    readTime: 9,
    publishDate: "2024-10-30",
    featured: true,
    tags: ["retirement", "planning"],
  },
  {
    slug: "whole-life-as-retirement-supplement",
    title: "Can Whole Life Insurance Supplement Your Retirement Income?",
    excerpt: "The cash value in a whole life policy can be tapped tax-advantageously. Here's how it works.",
    category: "retirement",
    readTime: 8,
    publishDate: "2024-11-06",
    tags: ["whole life", "cash value"],
  },
  {
    slug: "indexed-universal-life-retirement",
    title: "Indexed Universal Life Insurance as a Retirement Vehicle",
    excerpt: "IUL policies link growth to a market index — with a floor that protects against losses.",
    category: "retirement",
    readTime: 10,
    publishDate: "2024-11-11",
    tags: ["IUL", "universal life"],
  },
  {
    slug: "life-insurance-after-retirement",
    title: "Do You Still Need Life Insurance After You Retire?",
    excerpt: "The answer depends on your debts, dependents, and estate planning goals. Here's the framework.",
    category: "retirement",
    readTime: 7,
    publishDate: "2024-11-16",
    tags: ["retirement", "seniors"],
  },
  {
    slug: "pension-maximization-strategy",
    title: "Pension Maximization: Using Life Insurance to Protect Your Pension",
    excerpt: "Take the higher pension benefit and use life insurance to protect your spouse — the math often works out.",
    category: "retirement",
    readTime: 9,
    publishDate: "2024-11-21",
    tags: ["pension", "strategy"],
  },
  {
    slug: "life-insurance-vs-annuity",
    title: "Life Insurance vs. Annuity: Which Is Better for Retirement?",
    excerpt: "Both provide income security — but they work very differently. Here's a side-by-side comparison.",
    category: "retirement",
    readTime: 8,
    publishDate: "2024-12-04",
    tags: ["annuity", "comparison"],
  },
  {
    slug: "retirement-income-gap",
    title: "Life Insurance as a Solution for the Retirement Income Gap",
    excerpt: "Social Security and a 401(k) alone may not be enough. Life insurance can help bridge the gap.",
    category: "retirement",
    readTime: 7,
    publishDate: "2024-12-09",
    tags: ["income gap", "Social Security"],
  },
  {
    slug: "policy-loans-in-retirement",
    title: "Using Policy Loans in Retirement: A Tax-Advantaged Strategy",
    excerpt: "Borrowing against your life insurance cash value can generate tax-free income in retirement.",
    category: "retirement",
    readTime: 8,
    publishDate: "2024-12-16",
    tags: ["policy loans", "tax-free"],
  },
  {
    slug: "converting-term-to-permanent-insurance",
    title: "Converting Term Life to Permanent Insurance: When and How",
    excerpt: "Many term policies include a conversion option that lets you lock in permanent coverage before retirement.",
    category: "retirement",
    readTime: 7,
    publishDate: "2024-12-21",
    tags: ["conversion", "permanent"],
  },
  {
    slug: "life-insurance-at-60",
    title: "Life Insurance in Your 60s: What You Need and What to Skip",
    excerpt: "Your needs shift dramatically in your 60s. Here's how to right-size your coverage for this chapter.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-01-06",
    tags: ["over 60", "seniors"],
  },
  {
    slug: "1035-exchange-explained",
    title: "The 1035 Exchange: How to Switch Life Insurance Policies Without Tax",
    excerpt: "You can exchange one life policy for another — or for an annuity — without triggering a taxable event.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-01-11",
    tags: ["1035 exchange", "taxes"],
  },
  {
    slug: "social-security-and-life-insurance",
    title: "How Life Insurance and Social Security Work Together in Retirement",
    excerpt: "Smart coordination between these two income streams can maximize what your family receives.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-01-16",
    tags: ["Social Security", "coordination"],
  },
  {
    slug: "long-term-care-hybrid-policy",
    title: "Life Insurance + Long-Term Care: Hybrid Policies Explained",
    excerpt: "A single policy that covers both death and long-term care costs is gaining popularity — here's why.",
    category: "retirement",
    readTime: 9,
    publishDate: "2025-01-21",
    tags: ["long-term care", "hybrid"],
  },
  {
    slug: "surrender-cash-value-vs-policy-loan",
    title: "Surrendering Cash Value vs. Taking a Policy Loan: What's the Difference?",
    excerpt: "Both give you access to your policy's cash value — but they have very different tax and coverage implications.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-01-26",
    tags: ["cash value", "surrender"],
  },
  {
    slug: "life-insurance-for-401k-supplement",
    title: "Should You Use Life Insurance to Supplement Your 401(k)?",
    excerpt: "For high earners who've maxed out tax-advantaged accounts, permanent life insurance is worth a look.",
    category: "retirement",
    readTime: 8,
    publishDate: "2025-01-31",
    tags: ["401k", "supplement"],
  },
  {
    slug: "life-insurance-during-market-downturns",
    title: "How Life Insurance Protects Retirement Savings During Market Downturns",
    excerpt: "Unlike 401(k)s, certain life policies are sheltered from market volatility. Here's how that works.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-02-05",
    tags: ["market", "protection"],
  },
  {
    slug: "inherited-life-insurance-taxes",
    title: "Are Inherited Life Insurance Proceeds Taxable?",
    excerpt: "Generally no — but interest earnings, estate taxes, and policy structure can create exceptions.",
    category: "retirement",
    readTime: 6,
    publishDate: "2025-02-10",
    tags: ["inheritance", "taxes"],
  },
  {
    slug: "life-insurance-charitable-giving",
    title: "Using Life Insurance for Charitable Giving in Retirement",
    excerpt: "A life insurance policy can be a powerful legacy tool — giving significantly to the causes you love.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-02-15",
    tags: ["charity", "legacy"],
  },
  {
    slug: "modified-endowment-contract-explained",
    title: "Modified Endowment Contracts (MECs) Explained",
    excerpt: "Overfunding a life insurance policy can trigger MEC status, changing the tax treatment of loans and withdrawals.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-02-20",
    tags: ["MEC", "taxes"],
  },
  {
    slug: "life-insurance-for-non-working-spouse-retirement",
    title: "Life Insurance for a Non-Working Spouse in Retirement",
    excerpt: "Even without earned income, a non-working spouse has insurable value — especially for surviving partner support.",
    category: "retirement",
    readTime: 6,
    publishDate: "2025-02-25",
    tags: ["spouse", "non-working"],
  },
  {
    slug: "estate-equalization-life-insurance",
    title: "Using Life Insurance for Estate Equalization Among Heirs",
    excerpt: "When assets are hard to split (a business or property), life insurance can even out inheritances.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-03-03",
    tags: ["estate", "heirs"],
  },
  {
    slug: "life-insurance-at-70",
    title: "Can You Get Life Insurance at 70? What Options Remain",
    excerpt: "Yes — but your options narrow and prices rise. Here's what's realistically available in your 70s.",
    category: "retirement",
    readTime: 6,
    publishDate: "2025-03-08",
    tags: ["over 70", "seniors"],
  },
  {
    slug: "roth-ira-vs-whole-life",
    title: "Roth IRA vs. Whole Life Insurance: Which Is Better for Retirement?",
    excerpt: "Both offer tax advantages — but they serve different purposes. Here's how to choose.",
    category: "retirement",
    readTime: 9,
    publishDate: "2025-03-12",
    tags: ["Roth IRA", "whole life", "comparison"],
  },
  {
    slug: "early-retirement-life-insurance",
    title: "Life Insurance Strategies for Early Retirement (FIRE Movement)",
    excerpt: "Retiring at 45 or 50 changes your coverage math entirely. Here's how FIRE followers should think about insurance.",
    category: "retirement",
    readTime: 8,
    publishDate: "2025-03-16",
    tags: ["FIRE", "early retirement"],
  },
  {
    slug: "life-insurance-as-safe-money",
    title: "Life Insurance as 'Safe Money' in a Diversified Retirement Portfolio",
    excerpt: "Financial planners are increasingly including permanent life insurance as a non-correlated asset.",
    category: "retirement",
    readTime: 7,
    publishDate: "2025-03-20",
    tags: ["safe money", "portfolio"],
  },

  // ── PARENTS (25) ────────────────────────────────────────────────────
  {
    slug: "life-insurance-for-new-parents",
    title: "Life Insurance for New Parents: A Complete First-Timer's Guide",
    excerpt: "Having a baby is the single biggest trigger to buy life insurance. Here's everything you need to know.",
    category: "parents",
    readTime: 9,
    publishDate: "2024-10-24",
    featured: true,
    tags: ["new parents", "baby"],
  },
  {
    slug: "how-much-coverage-new-baby",
    title: "How Much Life Insurance Do You Need When You Have a Baby?",
    excerpt: "Income replacement, childcare costs, college savings — here's how to calculate the right coverage amount.",
    category: "parents",
    readTime: 7,
    publishDate: "2024-10-31",
    tags: ["coverage", "baby"],
  },
  {
    slug: "life-insurance-for-single-parents",
    title: "Life Insurance for Single Parents: Your Complete Coverage Guide",
    excerpt: "When you're the sole provider and sole caregiver, the stakes couldn't be higher. Here's how to protect your family.",
    category: "parents",
    readTime: 8,
    publishDate: "2024-11-07",
    tags: ["single parent"],
  },
  {
    slug: "child-life-insurance-worth-it",
    title: "Is Life Insurance for Children Worth Buying?",
    excerpt: "A controversial topic with real arguments on both sides. We break it down objectively.",
    category: "parents",
    readTime: 8,
    publishDate: "2024-11-13",
    tags: ["child life insurance"],
  },
  {
    slug: "life-insurance-while-pregnant",
    title: "Buying Life Insurance While Pregnant: What You Need to Know",
    excerpt: "Pregnancy affects underwriting — but most carriers will still issue coverage. Timing matters.",
    category: "parents",
    readTime: 7,
    publishDate: "2024-11-18",
    tags: ["pregnancy", "maternity"],
  },
  {
    slug: "life-insurance-after-adoption",
    title: "Life Insurance After Adoption: Updating Your Coverage",
    excerpt: "Adopting is a major financial event. Here's how to review and update your life insurance accordingly.",
    category: "parents",
    readTime: 6,
    publishDate: "2024-12-02",
    tags: ["adoption"],
  },
  {
    slug: "college-savings-vs-life-insurance",
    title: "529 Plan vs. Life Insurance for College Savings: A Comparison",
    excerpt: "Some whole life policies can fund college — but a 529 is usually the better pure savings vehicle.",
    category: "parents",
    readTime: 8,
    publishDate: "2024-12-08",
    tags: ["college", "529"],
  },
  {
    slug: "naming-guardian-in-life-insurance",
    title: "Naming a Guardian for Your Children in Your Life Insurance Plan",
    excerpt: "Your policy should work alongside your will and guardianship designation — here's how.",
    category: "parents",
    readTime: 6,
    publishDate: "2024-12-13",
    tags: ["guardian", "estate planning"],
  },
  {
    slug: "life-insurance-for-blended-families",
    title: "Life Insurance for Blended Families: Navigating Complex Coverage",
    excerpt: "Stepchildren, multiple beneficiaries, and competing obligations make blended family coverage uniquely challenging.",
    category: "parents",
    readTime: 8,
    publishDate: "2024-12-18",
    tags: ["blended family", "stepchildren"],
  },
  {
    slug: "parental-leave-and-life-insurance",
    title: "Should You Buy Life Insurance During Parental Leave?",
    excerpt: "You're home, you have time, and your coverage needs just changed dramatically. It's the perfect moment.",
    category: "parents",
    readTime: 5,
    publishDate: "2025-01-04",
    tags: ["parental leave"],
  },
  {
    slug: "life-insurance-for-military-parents",
    title: "Life Insurance for Military Parents: SGLI and Beyond",
    excerpt: "SGLI is a great starting point — but it's not always enough for families with civilian financial needs.",
    category: "parents",
    readTime: 7,
    publishDate: "2025-01-09",
    tags: ["military", "SGLI"],
  },
  {
    slug: "divorce-life-insurance-what-to-do",
    title: "Divorce and Life Insurance: What to Do with Your Policies",
    excerpt: "Divorce requires updating beneficiaries, reviewing coverage needs, and sometimes splitting policies.",
    category: "parents",
    readTime: 7,
    publishDate: "2025-01-14",
    tags: ["divorce"],
  },
  {
    slug: "life-insurance-for-stay-at-home-dad",
    title: "Life Insurance for Stay-at-Home Dads: You're Worth More Than You Think",
    excerpt: "Replace the cost of childcare, meals, transportation, and household management — it adds up fast.",
    category: "parents",
    readTime: 6,
    publishDate: "2025-01-19",
    tags: ["stay at home", "dad"],
  },
  {
    slug: "how-to-talk-to-kids-about-life-insurance",
    title: "How to Talk to Your Kids About Life Insurance (Without Scaring Them)",
    excerpt: "Age-appropriate conversations about financial protection can actually give children a sense of security.",
    category: "parents",
    readTime: 6,
    publishDate: "2025-01-24",
    tags: ["kids", "conversation"],
  },
  {
    slug: "protecting-college-age-children",
    title: "Life Insurance for College-Age Children: Parent and Student Options",
    excerpt: "When your kids head to college, coverage needs shift again. Here's what to consider.",
    category: "parents",
    readTime: 7,
    publishDate: "2025-01-29",
    tags: ["college", "young adult"],
  },
  {
    slug: "life-insurance-for-special-needs-child",
    title: "Life Insurance Planning for Parents of Special Needs Children",
    excerpt: "A child with special needs may require lifelong financial support — and that changes your coverage math entirely.",
    category: "parents",
    readTime: 9,
    publishDate: "2025-02-04",
    tags: ["special needs", "disability"],
  },
  {
    slug: "gifting-life-insurance-to-adult-children",
    title: "Gifting a Life Insurance Policy to Your Adult Children",
    excerpt: "Some parents pay premiums on a policy owned by a child — a powerful, tax-efficient gift.",
    category: "parents",
    readTime: 7,
    publishDate: "2025-02-09",
    tags: ["gift", "adult children"],
  },
  {
    slug: "family-income-benefit-rider",
    title: "The Family Income Benefit Rider: Monthly Payouts for Your Family",
    excerpt: "Instead of a lump sum, this rider provides monthly income — making budgeting easier for surviving families.",
    category: "parents",
    readTime: 6,
    publishDate: "2025-02-14",
    tags: ["riders", "income benefit"],
  },
  {
    slug: "life-insurance-for-gig-economy-parents",
    title: "Life Insurance for Parents in the Gig Economy",
    excerpt: "Freelancers, Uber drivers, and contractors don't get employer benefits — here's how to fill the gap.",
    category: "parents",
    readTime: 6,
    publishDate: "2025-02-19",
    tags: ["gig economy", "freelance"],
  },
  {
    slug: "second-marriage-life-insurance",
    title: "Life Insurance in a Second Marriage: Balancing Old and New Obligations",
    excerpt: "Second marriages create complex beneficiary questions. Here's how to handle them fairly and legally.",
    category: "parents",
    readTime: 7,
    publishDate: "2025-02-24",
    tags: ["second marriage", "beneficiary"],
  },
  {
    slug: "life-insurance-and-child-support",
    title: "Life Insurance and Child Support: What Divorced Parents Need to Know",
    excerpt: "Courts sometimes require the paying parent to maintain life insurance — here's how that works.",
    category: "parents",
    readTime: 7,
    publishDate: "2025-03-02",
    tags: ["divorce", "child support"],
  },
  {
    slug: "accelerated-death-benefit-for-parents",
    title: "Accelerated Death Benefits: Accessing Your Policy While Still Alive",
    excerpt: "Terminal illness riders let you access your death benefit early — a lifeline for seriously ill parents.",
    category: "parents",
    readTime: 6,
    publishDate: "2025-03-07",
    tags: ["accelerated benefit", "terminal illness"],
  },
  {
    slug: "life-insurance-trust-for-minors",
    title: "Setting Up a Life Insurance Trust for Your Minor Children",
    excerpt: "Leaving a large death benefit directly to a minor can create legal complications. A trust solves that.",
    category: "parents",
    readTime: 8,
    publishDate: "2025-03-11",
    tags: ["trust", "minor children"],
  },
  {
    slug: "how-to-leave-money-to-children-tax-free",
    title: "How to Leave Money to Your Children Tax-Free Using Life Insurance",
    excerpt: "Death benefits pass income-tax-free to beneficiaries — making life insurance one of the most efficient transfer tools.",
    category: "parents",
    readTime: 7,
    publishDate: "2025-03-15",
    tags: ["inheritance", "tax-free"],
  },
  {
    slug: "reviewing-life-insurance-school-age-child",
    title: "Reviewing Your Life Insurance When Your Kids Start School",
    excerpt: "New school year, new coverage review. Here's what to look at as your children grow.",
    category: "parents",
    readTime: 5,
    publishDate: "2025-03-19",
    tags: ["review", "school age"],
  },

  // ── SENIORS (25) ─────────────────────────────────────────────────────
  {
    slug: "best-life-insurance-for-seniors",
    title: "Best Life Insurance Options for Seniors in 2024",
    excerpt: "Coverage is still available in your 60s, 70s, and 80s. Here's what to look for — and what to avoid.",
    category: "seniors",
    readTime: 9,
    publishDate: "2024-10-26",
    featured: true,
    tags: ["seniors", "overview"],
  },
  {
    slug: "life-insurance-over-65",
    title: "Life Insurance After 65: What's Available and What It Costs",
    excerpt: "Rates rise with age, but smart shopping can still land you affordable coverage in your 60s.",
    category: "seniors",
    readTime: 7,
    publishDate: "2024-11-02",
    tags: ["over 65", "pricing"],
  },
  {
    slug: "life-insurance-over-75",
    title: "Life Insurance Over 75: Your Realistic Options",
    excerpt: "At 75+, options narrow — but final expense and guaranteed issue policies remain available.",
    category: "seniors",
    readTime: 7,
    publishDate: "2024-11-07",
    tags: ["over 75", "final expense"],
  },
  {
    slug: "life-insurance-for-retirees-on-social-security",
    title: "Life Insurance for Retirees Living on Social Security",
    excerpt: "Affordable coverage exists even on a fixed income. Here's how to find the right fit.",
    category: "seniors",
    readTime: 7,
    publishDate: "2024-11-12",
    tags: ["Social Security", "fixed income"],
  },
  {
    slug: "does-life-insurance-expire",
    title: "Does Your Life Insurance Expire? What Seniors Need to Know",
    excerpt: "Term policies have an end date. Permanent policies don't. Here's how to avoid an expiring-coverage crisis.",
    category: "seniors",
    readTime: 6,
    publishDate: "2024-11-17",
    tags: ["expiry", "term"],
  },
  {
    slug: "senior-life-insurance-no-exam",
    title: "No-Exam Life Insurance for Seniors: Best Policies in 2024",
    excerpt: "Instant approval, no needles — here are the top no-exam options for adults 60 and older.",
    category: "seniors",
    readTime: 7,
    publishDate: "2024-12-03",
    tags: ["no exam", "instant approval"],
  },
  {
    slug: "life-insurance-for-seniors-with-copd",
    title: "Life Insurance for Seniors with COPD",
    excerpt: "COPD doesn't automatically disqualify you. Here's what underwriters consider and which carriers are most lenient.",
    category: "seniors",
    readTime: 7,
    publishDate: "2024-12-09",
    tags: ["COPD", "health"],
  },
  {
    slug: "life-insurance-for-seniors-with-heart-disease",
    title: "Life Insurance for Seniors with Heart Disease",
    excerpt: "Heart conditions are common underwriting challenges — but approval is still possible with the right carrier.",
    category: "seniors",
    readTime: 7,
    publishDate: "2024-12-14",
    tags: ["heart disease", "health"],
  },
  {
    slug: "medicare-supplement-vs-life-insurance",
    title: "Medicare Supplement Insurance vs. Life Insurance: Not the Same Thing",
    excerpt: "These serve different purposes — and confusing them can leave seniors dangerously unprotected.",
    category: "seniors",
    readTime: 6,
    publishDate: "2024-12-19",
    tags: ["Medicare", "comparison"],
  },
  {
    slug: "life-insurance-for-widows",
    title: "Life Insurance for Widows and Widowers: Starting Over After Loss",
    excerpt: "Losing a spouse changes your coverage needs. Here's how to reassess and rebuild your protection.",
    category: "seniors",
    readTime: 7,
    publishDate: "2025-01-05",
    tags: ["widow", "widower"],
  },
  {
    slug: "life-insurance-for-grandparents",
    title: "Life Insurance for Grandparents: Protecting the Next Generation",
    excerpt: "Grandparents often want to leave something behind — here's how a policy can make that possible.",
    category: "seniors",
    readTime: 6,
    publishDate: "2025-01-10",
    tags: ["grandparents", "legacy"],
  },
  {
    slug: "whole-life-insurance-for-seniors",
    title: "Whole Life Insurance for Seniors: Pros, Cons, and Best Uses",
    excerpt: "Permanent coverage with a growing cash value — here's when whole life makes sense for older adults.",
    category: "seniors",
    readTime: 8,
    publishDate: "2025-01-15",
    tags: ["whole life"],
  },
  {
    slug: "cashing-out-life-insurance-policy",
    title: "Should You Cash Out Your Life Insurance Policy as a Senior?",
    excerpt: "Surrendering or selling a policy for cash has trade-offs. Here's how to weigh your options.",
    category: "seniors",
    readTime: 7,
    publishDate: "2025-01-20",
    tags: ["surrender", "cash value"],
  },
  {
    slug: "life-settlement-senior-options",
    title: "What Is a Life Settlement and Is It Right for You?",
    excerpt: "You can sell your life insurance policy for more than its cash surrender value. Here's how it works.",
    category: "seniors",
    readTime: 8,
    publishDate: "2025-01-25",
    tags: ["life settlement"],
  },
  {
    slug: "life-insurance-for-alzheimers-diagnosis",
    title: "Can You Get Life Insurance After an Alzheimer's Diagnosis?",
    excerpt: "A recent diagnosis significantly limits your options — but they're not zero. Here's what's available.",
    category: "seniors",
    readTime: 6,
    publishDate: "2025-01-30",
    tags: ["Alzheimer's", "dementia", "health"],
  },
  {
    slug: "long-term-care-planning-seniors",
    title: "Life Insurance and Long-Term Care: Planning Ahead for Senior Needs",
    excerpt: "Nursing home and assisted living costs can drain savings fast. A hybrid policy can help.",
    category: "seniors",
    readTime: 8,
    publishDate: "2025-02-04",
    tags: ["long-term care", "nursing home"],
  },
  {
    slug: "senior-burial-insurance-guide",
    title: "Senior Burial Insurance: What It Is and Where to Get It",
    excerpt: "Burial insurance is a small, whole life policy designed specifically for funeral coverage. Here's how to find a good one.",
    category: "seniors",
    readTime: 7,
    publishDate: "2025-02-09",
    tags: ["burial insurance", "final expense"],
  },
  {
    slug: "life-insurance-for-diabetic-seniors",
    title: "Life Insurance for Seniors with Diabetes: Rates and Options",
    excerpt: "Type 2 diabetes is extremely common in seniors — and most carriers will still offer coverage.",
    category: "seniors",
    readTime: 7,
    publishDate: "2025-02-14",
    tags: ["diabetes", "Type 2"],
  },
  {
    slug: "senior-term-life-insurance",
    title: "Can Seniors Get Term Life Insurance? Yes — Here's How",
    excerpt: "Term life is available up to age 80 at some carriers. It's often the most affordable option.",
    category: "seniors",
    readTime: 6,
    publishDate: "2025-02-19",
    tags: ["term life", "affordable"],
  },
  {
    slug: "life-insurance-after-stroke",
    title: "Life Insurance After a Stroke: What to Expect",
    excerpt: "A stroke in your history doesn't mean uninsurable. Timing and severity matter most.",
    category: "seniors",
    readTime: 6,
    publishDate: "2025-02-24",
    tags: ["stroke", "health"],
  },
  {
    slug: "protecting-assets-senior-estate",
    title: "Using Life Insurance to Protect Your Senior Estate",
    excerpt: "Estate taxes, probate, and IRA distributions can erode your legacy. Life insurance can offset those costs.",
    category: "seniors",
    readTime: 7,
    publishDate: "2025-03-01",
    tags: ["estate", "legacy"],
  },
  {
    slug: "premium-financing-seniors",
    title: "Premium Financing for Seniors: Funding a Large Policy Without Upfront Cost",
    excerpt: "High-net-worth seniors can fund large policies through premium financing — here's how it works.",
    category: "seniors",
    readTime: 8,
    publishDate: "2025-03-06",
    tags: ["premium financing", "high net worth"],
  },
  {
    slug: "life-insurance-for-overweight-seniors",
    title: "Life Insurance for Overweight Seniors: What Carriers Look For",
    excerpt: "Weight is a factor in underwriting — but with the right carrier, it doesn't have to be a deal-breaker.",
    category: "seniors",
    readTime: 6,
    publishDate: "2025-03-10",
    tags: ["weight", "BMI"],
  },
  {
    slug: "switching-carriers-as-senior",
    title: "Can Seniors Switch Life Insurance Carriers? What You Need to Know",
    excerpt: "Switching can save money — but you may give up guaranteed insurability. Here's how to evaluate the trade-off.",
    category: "seniors",
    readTime: 6,
    publishDate: "2025-03-14",
    tags: ["switch", "carriers"],
  },
  {
    slug: "joint-survivorship-life-insurance",
    title: "Second-to-Die (Survivorship) Life Insurance: A Guide for Senior Couples",
    excerpt: "A survivorship policy pays at the death of the second spouse — often used to cover estate taxes.",
    category: "seniors",
    readTime: 8,
    publishDate: "2025-03-18",
    tags: ["survivorship", "couples", "estate"],
  },

  // ── ESTATE PLANNING (25) ─────────────────────────────────────────────
  {
    slug: "life-insurance-estate-planning-basics",
    title: "Life Insurance and Estate Planning: The Foundation You Need",
    excerpt: "Life insurance is one of the most powerful tools in an estate plan. Here's why every plan should include it.",
    category: "estate-planning",
    readTime: 9,
    publishDate: "2024-10-29",
    featured: true,
    tags: ["basics", "estate"],
  },
  {
    slug: "irrevocable-life-insurance-trust",
    title: "Irrevocable Life Insurance Trusts (ILITs): A Complete Guide",
    excerpt: "An ILIT removes a life insurance policy from your taxable estate — potentially saving your heirs millions.",
    category: "estate-planning",
    readTime: 10,
    publishDate: "2024-11-05",
    tags: ["ILIT", "trust"],
  },
  {
    slug: "estate-tax-and-life-insurance",
    title: "Estate Taxes and Life Insurance: How to Protect Your Heirs",
    excerpt: "If your estate is large enough to trigger estate taxes, life insurance can pay that bill without liquidating assets.",
    category: "estate-planning",
    readTime: 9,
    publishDate: "2024-11-10",
    tags: ["estate tax"],
  },
  {
    slug: "life-insurance-as-inheritance",
    title: "Using Life Insurance as an Inheritance Tool",
    excerpt: "A properly structured policy can pass wealth to your heirs income-tax-free. Here's how.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2024-11-15",
    tags: ["inheritance"],
  },
  {
    slug: "business-succession-life-insurance",
    title: "Business Succession Planning with Life Insurance",
    excerpt: "When the owner dies, buy-sell agreements funded by life insurance ensure the business continues.",
    category: "estate-planning",
    readTime: 9,
    publishDate: "2024-11-20",
    tags: ["business", "succession"],
  },
  {
    slug: "charity-remainder-trust-life-insurance",
    title: "Charitable Remainder Trusts and Life Insurance: A Powerful Combination",
    excerpt: "Replace assets donated to charity by using the income stream to fund a life insurance policy.",
    category: "estate-planning",
    readTime: 9,
    publishDate: "2024-12-04",
    tags: ["charity", "CRT"],
  },
  {
    slug: "life-insurance-probate-avoidance",
    title: "How Life Insurance Helps Avoid Probate",
    excerpt: "Life insurance death benefits pass directly to named beneficiaries — bypassing the slow and costly probate process.",
    category: "estate-planning",
    readTime: 7,
    publishDate: "2024-12-09",
    tags: ["probate"],
  },
  {
    slug: "naming-trust-as-beneficiary",
    title: "Naming a Trust as Your Life Insurance Beneficiary: Pros and Cons",
    excerpt: "Useful for controlling how assets are distributed — but it adds complexity. Here's when it makes sense.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2024-12-14",
    tags: ["trust", "beneficiary"],
  },
  {
    slug: "life-insurance-for-farmland-preservation",
    title: "Life Insurance for Farmland and Family Business Preservation",
    excerpt: "Keeping the farm in the family when estate taxes loom large — life insurance is often the answer.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2024-12-19",
    tags: ["farmland", "family business"],
  },
  {
    slug: "key-person-insurance-business",
    title: "Key Person Life Insurance: Protecting Your Business from Loss",
    excerpt: "When a critical employee or founder dies, key person insurance provides capital to keep operating.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2025-01-05",
    tags: ["key person", "business"],
  },
  {
    slug: "life-insurance-for-estate-liquidity",
    title: "Creating Estate Liquidity with Life Insurance",
    excerpt: "Real estate and business interests are illiquid. Life insurance provides cash when heirs need it most.",
    category: "estate-planning",
    readTime: 7,
    publishDate: "2025-01-10",
    tags: ["liquidity", "estate"],
  },
  {
    slug: "generation-skipping-trust-insurance",
    title: "Generation-Skipping Trusts and Life Insurance",
    excerpt: "Pass wealth directly to grandchildren while minimizing transfer taxes with a GST and life insurance combo.",
    category: "estate-planning",
    readTime: 9,
    publishDate: "2025-01-15",
    tags: ["GST", "generation skipping"],
  },
  {
    slug: "life-insurance-and-will",
    title: "Life Insurance and Your Will: How They Work Together",
    excerpt: "Your will and your life insurance policy are separate legal documents. Here's how to align them.",
    category: "estate-planning",
    readTime: 7,
    publishDate: "2025-01-20",
    tags: ["will", "estate documents"],
  },
  {
    slug: "step-up-in-basis-life-insurance",
    title: "Step-Up in Basis and Life Insurance: Tax Planning for Heirs",
    excerpt: "Appreciated assets get a tax reset at death — understanding this interplay helps with estate design.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2025-01-25",
    tags: ["step-up basis", "taxes"],
  },
  {
    slug: "split-dollar-life-insurance",
    title: "Split Dollar Life Insurance Arrangements Explained",
    excerpt: "A split-dollar plan divides premium costs and benefits between employer and employee — a popular executive benefit.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2025-01-30",
    tags: ["split dollar", "executive"],
  },
  {
    slug: "life-insurance-for-divorce-decree",
    title: "Life Insurance Requirements in Divorce Decrees",
    excerpt: "Courts often order divorced parents to maintain life insurance as security for support obligations.",
    category: "estate-planning",
    readTime: 6,
    publishDate: "2025-02-04",
    tags: ["divorce", "decree"],
  },
  {
    slug: "annuity-replacement-with-life-insurance",
    title: "Replacing an Annuity with Life Insurance: When It Makes Sense",
    excerpt: "For the right client, swapping an annuity for permanent life insurance can improve tax efficiency.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2025-02-09",
    tags: ["annuity", "replacement"],
  },
  {
    slug: "wealth-transfer-using-life-insurance",
    title: "Wealth Transfer Strategies Using Life Insurance",
    excerpt: "Five advanced strategies high-net-worth families use to transfer wealth tax-efficiently with life insurance.",
    category: "estate-planning",
    readTime: 10,
    publishDate: "2025-02-14",
    tags: ["wealth transfer", "high net worth"],
  },
  {
    slug: "life-insurance-for-non-citizen-spouse",
    title: "Life Insurance and Estate Planning for Non-U.S. Citizen Spouses",
    excerpt: "Non-citizen spouses face different estate tax rules. Life insurance and QDOTs can help.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2025-02-19",
    tags: ["non-citizen", "QDOT"],
  },
  {
    slug: "life-insurance-premium-gifting",
    title: "Using Annual Gift Exclusions to Fund Life Insurance Premiums",
    excerpt: "The annual gift exclusion ($18,000 per recipient in 2024) can be used to pay premiums — a popular wealth transfer strategy.",
    category: "estate-planning",
    readTime: 7,
    publishDate: "2025-02-24",
    tags: ["gift exclusion", "premiums"],
  },
  {
    slug: "estate-planning-for-blended-families",
    title: "Estate Planning with Life Insurance for Blended Families",
    excerpt: "Second marriages and stepchildren make beneficiary planning complex. Here's a roadmap.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2025-03-01",
    tags: ["blended family", "beneficiary"],
  },
  {
    slug: "medicaid-planning-life-insurance",
    title: "Medicaid Planning and Life Insurance: What You Need to Know",
    excerpt: "Some life insurance policies count as assets for Medicaid purposes. Here's how to plan accordingly.",
    category: "estate-planning",
    readTime: 8,
    publishDate: "2025-03-06",
    tags: ["Medicaid", "long-term care"],
  },
  {
    slug: "when-to-update-estate-plan",
    title: "When to Update Your Estate Plan and Life Insurance",
    excerpt: "Life events trigger estate plan reviews. Here's a checklist of when to revisit both documents.",
    category: "estate-planning",
    readTime: 6,
    publishDate: "2025-03-10",
    tags: ["review", "update"],
  },
  {
    slug: "life-insurance-for-digital-assets",
    title: "Protecting Digital Assets with Life Insurance and Estate Planning",
    excerpt: "Cryptocurrency, websites, and online businesses need estate planning too — here's how insurance fits in.",
    category: "estate-planning",
    readTime: 7,
    publishDate: "2025-03-14",
    tags: ["digital assets", "crypto"],
  },
  {
    slug: "pet-trust-and-life-insurance",
    title: "Using Life Insurance to Fund a Pet Trust",
    excerpt: "Leave money specifically for the care of your pets with a pet trust funded by a life insurance policy.",
    category: "estate-planning",
    readTime: 5,
    publishDate: "2025-03-18",
    tags: ["pet trust", "pets"],
  },

  // ── VETERANS (25) ────────────────────────────────────────────────────
  {
    slug: "life-insurance-for-veterans",
    title: "Life Insurance for Veterans: A Complete Guide to Your Options",
    excerpt: "Transitioning out of service means leaving SGLI behind. Here's how to protect your family as a civilian.",
    category: "veterans",
    readTime: 9,
    publishDate: "2024-10-27",
    featured: true,
    tags: ["veterans", "overview"],
  },
  {
    slug: "vgli-vs-private-life-insurance",
    title: "VGLI vs. Private Life Insurance: Which Is Better?",
    excerpt: "Veterans' Group Life Insurance is convenient — but private coverage is often cheaper. Here's the full comparison.",
    category: "veterans",
    readTime: 8,
    publishDate: "2024-11-03",
    tags: ["VGLI", "comparison"],
  },
  {
    slug: "sgli-coverage-for-active-duty",
    title: "SGLI Coverage for Active Duty Service Members: What You Have",
    excerpt: "SGLI provides up to $500,000 in coverage during active service. Here's what that includes and what it doesn't.",
    category: "veterans",
    readTime: 7,
    publishDate: "2024-11-08",
    tags: ["SGLI", "active duty"],
  },
  {
    slug: "life-insurance-with-ptsd",
    title: "Life Insurance for Veterans with PTSD",
    excerpt: "PTSD can complicate underwriting — but many carriers offer coverage. Here's what to disclose and expect.",
    category: "veterans",
    readTime: 8,
    publishDate: "2024-11-13",
    tags: ["PTSD", "mental health"],
  },
  {
    slug: "disabled-veterans-life-insurance",
    title: "Life Insurance Options for Disabled Veterans",
    excerpt: "Service-connected disabilities affect your coverage options. Here's a guide to the programs available.",
    category: "veterans",
    readTime: 8,
    publishDate: "2024-11-18",
    tags: ["disabled veterans", "disability"],
  },
  {
    slug: "converting-sgli-to-civilian-coverage",
    title: "How to Convert SGLI to Civilian Life Insurance After Discharge",
    excerpt: "You have 120 days after discharge to convert SGLI to private coverage. Don't miss this window.",
    category: "veterans",
    readTime: 7,
    publishDate: "2024-12-03",
    tags: ["SGLI", "conversion", "discharge"],
  },
  {
    slug: "life-insurance-for-military-spouses",
    title: "Life Insurance for Military Spouses: Coverage While Your Partner Deploys",
    excerpt: "Military spouses face unique financial risks. Here's how to build a comprehensive protection plan.",
    category: "veterans",
    readTime: 7,
    publishDate: "2024-12-08",
    tags: ["military spouse", "deployment"],
  },
  {
    slug: "va-life-insurance-programs-overview",
    title: "VA Life Insurance Programs: A Complete Overview",
    excerpt: "SGLI, VGLI, SDVI, VGLI — there are more VA programs than most veterans realize. Here's how they compare.",
    category: "veterans",
    readTime: 9,
    publishDate: "2024-12-13",
    tags: ["VA", "programs"],
  },
  {
    slug: "service-disabled-veterans-insurance",
    title: "Service-Disabled Veterans' Insurance (S-DVI): How to Apply",
    excerpt: "Veterans with a VA-rated disability may qualify for S-DVI — a special government life insurance program.",
    category: "veterans",
    readTime: 7,
    publishDate: "2024-12-18",
    tags: ["S-DVI", "disabled"],
  },
  {
    slug: "life-insurance-with-combat-related-injuries",
    title: "Life Insurance for Veterans with Combat-Related Injuries",
    excerpt: "Injuries from deployment affect underwriting. Here's how to navigate the private insurance market as a combat vet.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-01-04",
    tags: ["combat injuries", "underwriting"],
  },
  {
    slug: "national-guard-reserves-life-insurance",
    title: "Life Insurance for National Guard and Reserve Members",
    excerpt: "Guard and Reserve members have different coverage timelines than active duty. Here's what to know.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-01-09",
    tags: ["National Guard", "Reserves"],
  },
  {
    slug: "veteran-owned-life-insurance-benefits",
    title: "Additional Life Insurance Benefits for Veterans You May Not Know About",
    excerpt: "State programs, nonprofit resources, and carrier discounts specifically for veterans.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-01-14",
    tags: ["benefits", "programs"],
  },
  {
    slug: "life-insurance-after-military-retirement",
    title: "Life Insurance After Military Retirement: What Changes",
    excerpt: "Military retirement brings a pension — but it also means losing group coverage. Here's how to bridge the gap.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-01-19",
    tags: ["retirement", "pension"],
  },
  {
    slug: "vgli-rate-increases-veterans",
    title: "VGLI Rate Increases: Why Veterans Often Switch to Private Coverage",
    excerpt: "VGLI premiums increase with age and can become very expensive. Here's when to consider making the switch.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-01-24",
    tags: ["VGLI", "rates"],
  },
  {
    slug: "life-insurance-with-tbi",
    title: "Life Insurance for Veterans with Traumatic Brain Injury (TBI)",
    excerpt: "TBI ranges widely in severity. Here's how underwriters evaluate it and what coverage looks like.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-01-29",
    tags: ["TBI", "brain injury"],
  },
  {
    slug: "suicide-exclusions-veteran-life-insurance",
    title: "Suicide Exclusions in Life Insurance: What Veterans Need to Know",
    excerpt: "Standard policies include a 2-year suicide exclusion. Here's how it works and what veterans should understand.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-02-03",
    tags: ["suicide exclusion", "mental health"],
  },
  {
    slug: "life-insurance-for-female-veterans",
    title: "Life Insurance for Female Veterans: Special Considerations",
    excerpt: "Female veterans face unique health and coverage challenges. Here's a guide to finding the right policy.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-02-08",
    tags: ["female veterans"],
  },
  {
    slug: "veteran-mortgage-protection-va-loan",
    title: "Mortgage Protection for Veterans Using VA Loans",
    excerpt: "VA loans are a great benefit — pairing them with mortgage protection keeps your family in their home.",
    category: "veterans",
    readTime: 6,
    publishDate: "2025-02-13",
    tags: ["VA loan", "mortgage protection"],
  },
  {
    slug: "agent-orange-life-insurance",
    title: "Life Insurance for Vietnam Veterans Exposed to Agent Orange",
    excerpt: "Agent Orange exposure causes a range of conditions that complicate underwriting. Here's what options remain.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-02-18",
    tags: ["Agent Orange", "Vietnam"],
  },
  {
    slug: "veteran-financial-planning-guide",
    title: "A Veteran's Complete Financial Planning Guide",
    excerpt: "Pensions, disability benefits, GI Bill, life insurance — here's how to build a complete financial plan.",
    category: "veterans",
    readTime: 10,
    publishDate: "2025-02-23",
    tags: ["financial planning", "comprehensive"],
  },
  {
    slug: "military-family-life-insurance-checklist",
    title: "Military Family Life Insurance Checklist: Coverage at Every Stage",
    excerpt: "From enlistment to retirement, here's how your coverage needs evolve through a military career.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-02-28",
    tags: ["checklist", "military"],
  },
  {
    slug: "life-insurance-for-veterans-over-60",
    title: "Life Insurance for Veterans Over 60: Finding Affordable Coverage",
    excerpt: "Many vets in their 60s are still carrying VGLI. Here's whether switching to private coverage makes sense.",
    category: "veterans",
    readTime: 6,
    publishDate: "2025-03-05",
    tags: ["over 60", "VGLI"],
  },
  {
    slug: "veteran-final-expense-planning",
    title: "Final Expense Planning for Veterans: Benefits and Insurance Combined",
    excerpt: "Veterans may qualify for burial benefits from the VA — here's how that fits with private final expense coverage.",
    category: "veterans",
    readTime: 7,
    publishDate: "2025-03-09",
    tags: ["final expense", "burial benefits"],
  },
  {
    slug: "reserve-duty-life-insurance-gap",
    title: "The Reserve Duty Life Insurance Gap: Coverage During Activation",
    excerpt: "SGLI activates when you deploy — but what covers you between activations? Here's how to fill the gap.",
    category: "veterans",
    readTime: 6,
    publishDate: "2025-03-13",
    tags: ["Reserves", "deployment"],
  },
  {
    slug: "honoring-veterans-with-life-insurance",
    title: "Honor Your Service with a Legacy: Using Life Insurance as a Veteran",
    excerpt: "Life insurance is one of the most powerful ways veterans can protect and provide for the family they fought for.",
    category: "veterans",
    readTime: 6,
    publishDate: "2025-03-17",
    tags: ["legacy", "family"],
  },
];

export const FEATURED_ARTICLES = ALL_ARTICLES.filter((a) => a.featured);

export function getArticlesByCategory(category: ArticleCategory): Article[] {
  return ALL_ARTICLES.filter((a) => a.category === category);
}

export function getArticleBySlug(slug: string): Article | undefined {
  return ALL_ARTICLES.find((a) => a.slug === slug);
}

export function getRelatedArticles(article: Article, limit = 3): Article[] {
  return ALL_ARTICLES.filter(
    (a) => a.category === article.category && a.slug !== article.slug
  ).slice(0, limit);
}
